Project/Controllers/DetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Project.Controllers
{
    public class DetailsController : Controller
    {
        // GET: Details
        public ActionResult Index()
        {
            return View();
        }
    }
}

Project/Controllers/StoresController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Project
{
    public class StoresController : Controller
    {
        private Entities_new db = new Entities_new();

        // GET: Stores
        public ViewResult Index(string sortOrder, string searchString)
        {
            ViewBag.BrandSortParm = String.IsNullOrEmpty(sortOrder) ? "Brand_desc" : "";

            var store = from p in db.Stores
                        select p;

            if (!String.IsNullOrEmpty(searchString))
            {
                store = store.Where(p => p.name.ToUpper().Contains(searchString.ToUpper()));

            }

           /* switch (sortOrder)
            {
                case "Brand_desc":
                    phone = phone.OrderByDescending(p => p.brand);
                    break;
                default:
                    phone = phone.OrderBy(p => p.product_id);
                    break;
            }*/

            return View(store);
        }
        // GET: Stores/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Store store = db.Stores.Find(id);
            if (store == null)
            {
                return HttpNotFound();
            }
            return View(store);
        }

        // GET: Stores/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Stores/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "product_id,url,name,time,Review")] Store store)
        {
            if (ModelState.IsValid)
            {
                var file = Request.Files[0];

                if (file != null && file.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(file.FileName);
                    var path = Path.Combine(Server.MapPath("~/Content/images"), fileName);
                    file.SaveAs(path);
                    store.url = fileName;
                }
                db.Stores.Add(store);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(store);
        }

        // GET: Stores/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Store store = db.Stores.Find(id);
            if (store == null)
            {
                return HttpNotFound();
            }
            return View(store);
        }

        // POST: Stores/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "product_id,url,name,time,Review")] Store store)
        {
            if (ModelState.IsValid)
            {
                db.Entry(store).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(store);
        }

        // GET: Stores/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Store store = db.Stores.Find(id);
            if (store == null)
            {
                return HttpNotFound();
            }
            return View(store);
        }

        // POST: Stores/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Store store = db.Stores.Find(id);
            db.Stores.Remove(store);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Project/Views/Stores/Create.cshtml
@model Project.Store

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Stores", FormMethod.Post, new{enctype= "multipart/form-data"}))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Store</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.url, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.url, new { htmlAttributes = new { @class = "form-control", type = "file" } })
                @Html.ValidationMessageFor(model => model.url, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.time, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.time, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.time, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Review, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Review, new { htmlAttributes = new { @class = "form-control"  } })
                @Html.ValidationMessageFor(model => model.Review, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Project/Views/Stores/Delete.cshtml
@model Project.Store

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Store</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.url)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.url)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.time)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.time)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Review)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Review)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Project/Views/Stores/Details.cshtml
@model Project.Store

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Store</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.url)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.url)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.time)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.time)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Review)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Review)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.product_id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Project/Views/Stores/Edit.cshtml
@model Project.Store

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Store</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.product_id)

        <div class="form-group">
            @Html.LabelFor(model => model.url, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.url, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.url, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.time, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.time, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.time, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Review, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Review, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Review, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Project/Views/Stores/Index.cshtml
@model IEnumerable<Project.Store>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Shop Homepage - Start Bootstrap Template</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="@Url.Content("~/Content/Style1.css")" rel="stylesheet" type="text/css" />
    <link href="css/styles.css" rel="stylesheet" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Prompt&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

</head>

<body>
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container px-4 px-lg-5">
            <b><a class="navbar-brand" href="@Url.Action("Index", "Home")">SUT IN SIDE</a></b>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">

                <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                   <!-- <li class="nav-item"><a class="nav-link active" aria-current="page" href="#!">Home</a></li>
                    <li class="nav-item"><a class="nav-link" href="#!">About</a></li>
                    
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Shop</a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="#!">All Products</a></li>
                            <li><hr class="dropdown-divider" /></li>
                            <li><a class="dropdown-item" href="#!">Popular Items</a></li>
                            <li><a class="dropdown-item" href="#!">New Arrivals</a></li>
                        </ul>
                    </li>-->

                </ul>

                <form class="d-flex">
                    <!--<button class="btn btn-outline-dark" type="submit">-->
                    <!--<i class="bi-cart-fill me-1"></i>-->
                    @Html.ActionLink("เพิ่มร้านค้า", "Create", null, new { @class = "btn btn-success" })
                    <!--<span class="badge bg-dark text-white ms-1 rounded-pill">0</span>-->
                    <!--</button>-->
                </form>
            </div>
        </div>
    </nav>

    <!-- Header-->
    <br />
    <header class="bg-dark-edit py-5">

        <div class="container px-4 px-lg-5 my-5">
            <!--<div class="text-center text-black">-->
            <p><span class="display-4 fw-bolder">สมศรี มีสุข</span></p>
            <p><span class="lead fw-normal text-black-50 mb-0">คะแนนสะสมของคุณ : 7500 point</span></p>
            <!--<h1 class="display-4 fw-bolder">สมศรี มีสุข</h1>-->
            <!--<p class="lead fw-normal text-black-50 mb-0">500 point</p>-->
            <!--<div class="bg-dark-edit-in">
                <p class="text-black-50-edit">ค้นหามื้ออาหารอร่อย ตรงนี้ !</p>
            </div>-->
            <!--<div class="div-edit text-black-50-edit">ค้นหามื้ออาหารอร่อย ตรงนี้ !</div>-->

            <div class="example">
                @using ((Html.BeginForm()))
                {
                    @Html.TextBox("searchString", null, new { @placeholder = "ค้นหามื้ออาหารอร่อย ตรงนี้ !" })
                    <button type="submit"><i class="fa fa-search"></i></button>
                }

            </div>


        </div>
        <!--</div>-->

    </header>

    <!--<div class="container">
        <div class="row">
            <div class="col text-right">
                @Html.ActionLink("เพิ่มร้านค้า", "Create", null, new { @class = "btn btn-success" })
            </div>
        </div>
    </div>
    <br />

    <div class="container">
        <div class="row">
            <div class="div-edit text-black-50-edit">
                @using ((Html.BeginForm()))
                {
                    @Html.TextBox("searchString", null, new { @placeholder = "ค้นหาชื่อร้านค้า" })
                    <input type="submit" class="btn btn-info" value="Search" />
                }
            </div>
        </div>
    </div>-->

    <section class="py-5">

        @*แนะนำร้านอาหารเกิดใหม่*@
        <div class="container px-4 px-lg-5 mt-5">
            <div class="divider-custom divider-light">
                <h1 style="color: white; font-size: 42px">แนะนำร้านอาหารเกิดใหม่</h1>
                <div class="divider-custom-line"></div>
            </div>

            @for (var i = 1; i <= Model.ToList().Count(); i++)
            {
                var indexItem = i - 1;
                if (i == 1 || i % 4 == 1)
                {
                    @:<div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                    }
                    <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Status New-->
                            <div class="badge bg-danger text-white position-absolute" style="top: 0.5rem; right: 0.5rem">New!</div>
                            <!-- Product image -->
                            <img class="card-img-top" src="@Url.Content("~/Content/images/" + (Model.ElementAt(indexItem).url))" alt="..." />
                            <!-- <img class="img-responsive" style="max-width: 70%;" src=@Url.Content("~/Content/images/" + (Model.ElementAt(indexItem).url)) /> -->
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">@Model.ElementAt(indexItem).name</h5>
                                    <!-- Product reviews-->
                                    <div class="d-flex justify-content-center small text-warning mb-2">
                                        @for (var s = 1; s <= Model.ElementAt(indexItem).Review; s++)
                                        {
                                            <div class="bi-star-fill"></div>
                                        }
                                    </div>
                                    <!-- time -->
                                    @Model.ElementAt(indexItem).time
                                </div>
                            </div>


                            <!-- Product actions-->
                            <div class="pt-0 border-top-0 bg-transparent">
                                <div class="text-center">
                                    @*<a class="btn btn-outline-dark mt-auto" href="@Url.Action("Index", "Details")">ดูเพิ่มเติม</a>*@
                                    @Html.ActionLink("Details", "Details", new { id = @Model.ElementAt(indexItem).product_id }, new { @class = "btn btn-outline-dark mt-auto" })
                                    @Html.ActionLink("Edit", "Edit", new { id = @Model.ElementAt(indexItem).product_id }, new { @class = "btn btn-warning" })
                                    @Html.ActionLink("Delete", "Delete", new { id = @Model.ElementAt(indexItem).product_id }, new { @class = "btn btn-danger" })
                                </div>
                            </div>
                            <br />

                            <!--<div class="caption">
                                <h3> @Model.ElementAt(indexItem).name </h3>
                                <h5> @Model.ElementAt(indexItem).time </h5>
                                <h5> @Model.ElementAt(indexItem).Review </h5>
                                @Html.ActionLink("Details", "Details", new { id = @Model.ElementAt(indexItem).product_id }, new { @class = "btn btn-info" })
                                @Html.ActionLink("Edit", "Edit", new { id = @Model.ElementAt(indexItem).product_id }, new { @class = "btn btn-warning" })
                                @Html.ActionLink("Delete", "Delete", new { id = @Model.ElementAt(indexItem).product_id }, new { @class = "btn btn-danger" })

                            </div>-->

                        </div>

                    </div>
                    if (i % 4 == 0)
                    {
                    @:</div>
                }
            }
        </div>
        @*แนะนำร้านอาหารเกิดใหม่*@

    </section>

    <!--<table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.url)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.time)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Review)
            </th>
            <th></th>
        </tr>


    @foreach (var item in Model)
    {
        <tr>
            <td>
                <img src=@Url.Content("~/Content/images/"+(item.url)) style="width: 100px;height: auto" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.time)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Review)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.product_id }) |
                @Html.ActionLink("Details", "Details", new { id = item.product_id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.product_id })
            </td>
        </tr>
    }

    </table>-->
</body>
</html>